### ISSUE TITLE
Redirect for Compression Streams

### ISSUE THREAD

**Issue by annevk** [WICG/wicg.github.io#24]
https://wicg.github.io/compression/ needs to redirect to https://compression.spec.whatwg.org/

(Neither is currently up at the moment, but hopefully we'll get that sorted quickly. See https://github.com/whatwg/sg/issues/231 for details.)

cc @domenic @foolip

**Comment by yoavweiss** [comment]
Fixed with https://github.com/WICG/wicg.github.io/commit/c0a6a466934ddf7c8d217f3a3386a654007dcc0d
